[package]
authors = ["Andy Russell <arussell123@gmail.com>"]
description = "A complete solution for previewing markdown."
documentation = "https://euclio.github.io/aurelius"
homepage = "https://github.com/euclio/aurelius"
keywords = ["markdown", "vim"]
license = "MIT/Apache-2.0"
name = "aurelius"
readme = "README.md"
repository = "https://github.com/euclio/aurelius"
version = "0.1.9"

[dependencies]
chan = "0.1.14"
hoedown = "5.0.0"
log = "0.3.1"
nickel = { git = "https://github.com/Ryman/nickel.rs", branch = "expose_listener" }
porthole = "0.1.0"
url = "1.1.0"
websocket = "~0.17.0"

[dev-dependencies]
hyper = "0.9.4"
